/*
 * SaveSelection.java
 *
 * Created on 19.6.2009, 14:09:23
 */

package kandrm.JLatVis.gui.selection;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kandrm.JLatVis.lattice.editing.selection.SavedSelections;
import kandrm.JLatVis.lattice.editing.selection.Selection;
import kandrm.JLatVis.lattice.editing.selection.Selector;

/**
 *
 * @author Michal Kandr
 */
public class SaveSelection extends javax.swing.JDialog {
    private Selector selector;
    private SavedSelections savedSelections;

    /** Creates new form SaveSelection */
    public SaveSelection(java.awt.Frame parent, Selector selector, SavedSelections savedSelections) {
        super(parent, true);
        initComponents();

        this.selector = selector;
        this.savedSelections = savedSelections;
        
        nameField.getDocument().addDocumentListener(new DocumentListener() {
            private void changeOkEnabled(){
                okButton.setEnabled( nameField.getText().length() > 0 );
            }

            public void insertUpdate(DocumentEvent e) {
                changeOkEnabled();
            }
            public void removeUpdate(DocumentEvent e) {
                changeOkEnabled();
            }
            public void changedUpdate(DocumentEvent e) {
                changeOkEnabled();
            }
        });
    }

    public void setSelector(Selector selector) {
        this.selector = selector;
    }

    public void setSavedSelections(SavedSelections savedSelections) {
        this.savedSelections = savedSelections;
    }

    @Override
    public void setVisible(boolean visible){
        super.setVisible(visible);
        nameField.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        stornoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selection save");
        setModal(true);

        jLabel1.setText("Selection name");

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        stornoButton.setText("Storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stornoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(stornoButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(stornoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stornoButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_stornoButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        savedSelections.saveSelection(new Selection(nameField.getText(), selector.getSelectedItems()));
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton stornoButton;
    // End of variables declaration//GEN-END:variables

}
