package kandrm.JLatVis.gui.settings.visual;

import kandrm.JLatVis.guiConnect.settings.visual.EdgeModel;
import java.awt.Frame;
import kandrm.JLatVis.gui.GuiUtils;
import kandrm.JLatVis.lattice.editing.history.History;
import kandrm.JLatVis.lattice.visual.settings.patterns.EdgeSettingPattern;

/**
 *
 * @author Michal Kandr
 */
public class EdgeSettings extends javax.swing.JDialog {
    private EdgeModel settingsModel;
    private boolean isSearch;

    private History history;

    public EdgeSettings(Frame parent){
        this(parent, false);
    }
    public EdgeSettings(Frame parent, boolean isSearch) {
        this(parent, new EdgeModel(), isSearch);
    }
    public EdgeSettings(Frame parent, EdgeModel settings, boolean isSearch) {
        super(parent, true);
        this.isSearch = isSearch;
        initComponents();
        settingsModel = settings;
        setDefaultValues();
        if(isSearch){
            setTitle("Edge visual search");
        }
    }

    public EdgeModel getModel(){
        return settingsModel;
    }
    public void setModel(EdgeModel settings) {
        settings.setHistory(history);
        settingsModel = settings;
    }
    
    public void setHistory(History history){
        this.history = history;
        settingsModel.setHistory(history);
    }

    @Override
    public void setVisible(boolean visible){
        if(visible){
            if( ! isSearch && settingsModel.size() < 1){
                GuiUtils.showSetNoSel(getParent(), "edges");
                return;
            }
            setDefaultValues();
        }
        super.setVisible(visible);
    }

    private void setDistance(Integer distance){
        SettingUtils.showDisableIfNull(distanceDisable, distance, isSearch);
        if(distance != null){
            distanceSpinner.setValue(distance);
        }
    }
    private Integer getDistance(){
        return distanceDisable.isSelected() ? null : Integer.parseInt(distanceSpinner.getValue().toString());
    }

    /*private void setEdgeVisible(Boolean visible){
        SettingUtils.showDisableIfNull(visibleDisable, visible, isSearch);
        if(visible != null){
            visibleCheckBox.setSelected(visible);
        }
    }
    private Boolean getEdgeVisible(){
        return visibleDisable.isSelected() ? null : visibleCheckBox.isSelected();
    }*/
        

    private void setDefaultValues(){
        EdgeSettingPattern settingPattern = settingsModel.getSettingPattern();

        //setEdgeVisible(settingPattern.getVisible());
        setDistance(settingPattern.getDistanceFromNode());

        lineSetting.setLineWidth(settingPattern.getWidth());
        lineSetting.setLineDashing(settingPattern.getDashing());
        lineSetting.setLineColor(settingPattern.getColor());
    }

    private void saveSettings(){
        EdgeSettingPattern newPattern = new EdgeSettingPattern(
            lineSetting.getLineColor(),
            lineSetting.getLineWidth(),
            lineSetting.getLineDashing(),

            null,
            getDistance()
        );
        settingsModel.setSettingPattern(newPattern);
        settingsModel.apply();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        distanceLabel = new javax.swing.JLabel();
        distanceDisable = new javax.swing.JCheckBox();
        distanceSpinner = new javax.swing.JSpinner();
        linePanel = new javax.swing.JPanel();
        lineSetting = new kandrm.JLatVis.gui.settings.visual.LineSetting(isSearch);
        jPanel5 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edge visual settings");
        setResizable(false);

        generalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        distanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        distanceLabel.setText("Distance from node");
        distanceLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(distanceLabel, gridBagConstraints);

        distanceDisable.setText(SettingUtils.getDisableText(isSearch));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(distanceDisable, gridBagConstraints);

        distanceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        distanceSpinner.setPreferredSize(new java.awt.Dimension(60, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, distanceDisable, org.jdesktop.beansbinding.ELProperty.create("${ ! selected}"), distanceSpinner, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(distanceSpinner, gridBagConstraints);

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", generalPanel);

        linePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        linePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        linePanel.add(lineSetting);

        jTabbedPane1.addTab("Line", linePanel);

        saveButton.setText(isSearch ? "Search" : "Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancelButton)
                .addComponent(saveButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveSettings();
        dispose();
}//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox distanceDisable;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JSpinner distanceSpinner;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel linePanel;
    private kandrm.JLatVis.gui.settings.visual.LineSetting lineSetting;
    private javax.swing.JButton saveButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}